### ISSUE TITLE
Publish Code Coverage Report step is Failing

### ISSUE THREAD

**Issue by super-jb** [SeanKilleen/ExampleTestResultsWithGithubActions#9]
I copied your `build.yaml` file into my solution and getting the following error:
  
The only difference is that I'm setting this to only execute on PRs against `develop`:
```
on:
  pull_request:
    branches: ["develop"]
```

![image](https://github.com/SeanKilleen/ExampleTestResultsWithGithubActions/assets/6843604/67bfef71-72e1-4ed7-835b-0d86ca97fd20)

```
Run irongut/CodeCoverageSummary@v1.3.0
  with:
    filename: Cobertura.xml
    badge: true
    fail_below_min: false
    format: markdown
    hide_branch_rate: false
    hide_complexity: false
    indicators: true
    output: both
    thresholds: 10 30
  env:
    REGISTRY: ghcr.io
    IMAGE_NAME: MyCompany/MyCompany.api
    DOTNET_ROOT: /usr/share/dotnet
/usr/bin/docker run --name ghcrioirongutcodecoveragesummaryv130_9d163[2](https://github.com/MyCompany/MyCompany.api/actions/runs/9229821806/job/25396804878#step:9:2) --label 5c[3](https://github.com/MyCompany/MyCompany.api/actions/runs/9229821806/job/25396804878#step:9:3)6b5 --workdir /github/workspace --rm -e "REGISTRY" -e "IMAGE_NAME" -e "DOTNET_ROOT" -e "INPUT_FILENAME" -e "INPUT_BADGE" -e "INPUT_FAIL_BELOW_MIN" -e "INPUT_FORMAT" -e "INPUT_HIDE_BRANCH_RATE" -e "INPUT_HIDE_COMPLEXITY" -e "INPUT_INDICATORS" -e "INPUT_OUTPUT" -e "INPUT_THRESHOLDS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/MyCompany.api/MyCompany.api":"/github/workspace" ghcr.io/irongut/codecoveragesummary:v1.3.0  "--files" "Cobertura.xml" "--badge" "true" "--fail" "false" "--format" "markdown" "--hidebranch" "false" "--hidecomplexity" "false" "--indicators" "true" "--output" "both" "--thresholds" "[10](https://github.com/MyCompany/MyCompany.Api/actions/runs/9229821806/job/25396804878#step:9:10) 30"
Coverage File: /github/workspace/Cobertura.xml
Parsing Error: No package data found - /github/workspace/Cobertura.xml
```

Any idea what the problem could be @SeanKilleen?

[build.txt](https://github.com/SeanKilleen/ExampleTestResultsWithGithubActions/files/15440217/build.txt) (copy paste of my `.yaml` as `.txt` -> gh won't allow me to attach a `.yaml` file)

**Comment by super-jb** [comment]
Thanks for the reply @SeanKilleen. I was messing around trying to get this to work and forgot to change that back. Still getting the exact same error:
```
Coverage File: /github/workspace/Cobertura.xml
Parsing Error: No package data found - /github/workspace/Cobertura.xml
```
Am I missing some dependency? Dopes something need to be configured in my GH repo for this to work?
 
[build.txt](https://github.com/SeanKilleen/ExampleTestResultsWithGithubActions/files/15445613/build.txt)

**Comment by SeanKilleen** [comment]
@super-jb when you go to the summary of your build, do you see a coverage file in your artifacts? 

When you download that and unzip it, do you see a Cobertura.xml file?

![image](https://github.com/SeanKilleen/ExampleTestResultsWithGithubActions/assets/2148318/98a0dcb0-6232-44d0-b48d-870986854d39)

I'm wondering if the file isn't being produced. I can't see your build logs to confirm.

**Comment by super-jb** [comment]
@SeanKilleen, yes the `coverage` file is created:

![Summary - Coverage xml](https://github.com/SeanKilleen/ExampleTestResultsWithGithubActions/assets/6843604/82c79efe-6f16-4504-b63f-145e9c90309f)

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage line-rate="1" branch-rate="1" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0" complexity="NaN" version="0" timestamp="1716775553">
  <sources />
  <packages />
</coverage>
```
[Cobertura.txt](https://github.com/SeanKilleen/ExampleTestResultsWithGithubActions/files/15450123/Cobertura.txt)


I've also attached some images from my latest (failed build)
![Publish Code Coverage Report](https://github.com/SeanKilleen/ExampleTestResultsWithGithubActions/assets/6843604/fd6b0da4-11ab-4362-a318-809864a6a384)

[Publish Code Coverage Report.txt](https://github.com/SeanKilleen/ExampleTestResultsWithGithubActions/files/15450132/Publish.Code.Coverage.Report.txt)

**Comment by super-jb** [comment]
@SeanKilleen, by any chance, is your repo under a GitHub Enterprise account? 
Could there be some underlying permission that you _just_ have that I don't?

**Comment by super-jb** [comment]
Many thanks (once again for getting back to me @SeanKilleen). I appreciate your help on this.

So, I had 2 test projects but using xUnit instead of NUnit. So removed them both and just focused on 1 project setup using NUnit, just like in your examples. My project is basically identical to yours. Only differences:
* Microsoft.NET.Test.Sdk
   * yours: v17.9.0
   * mine: v17.10.0
* I've added FluentAssertions library  
![image](https://github.com/SeanKilleen/ExampleTestResultsWithGithubActions/assets/6843604/83555d5f-60d1-4895-8738-ea130587be06)

Pushed these changes and created a PR... same result 😞- Failure on the `Publish Code Coverage Report` section
```
Coverage File: /github/workspace/Cobertura.xml
Parsing Error: No package data found - /github/workspace/Cobertura.xml
```
My `coverage.xml` report is the same as the one I shared in a previous comment. 

So, let's backtrack to the previous steps. Seems like the problem is that the `Cobertura.xml` file is not written to properly. 

I got a screenshot side by side of your build and my build of the previous 2 steps and outlined some of the visible differences:
* Left is your successful build
* Right is my failed build
* The `Combine Coverage Reports` section seems identical (other than a minor upgrade of the .net version on my end)
   * 1 should not make assumptions but just going to guess this is not the problem
* Seems like the `Upload Combined Coverage XML` is where the problem may be, since in my build, it always writes a minimal output into the `.xml` (that's only 350 bytes):
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage line-rate="1" branch-rate="1" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0" complexity="NaN" version="0" timestamp="1717083805">
  <sources />
  <packages />
</coverage>
```
![image](https://github.com/SeanKilleen/ExampleTestResultsWithGithubActions/assets/6843604/c68f8630-6341-46b1-9727-d11b0bafb6ac)

So the file is created successfully, but for whatever reason I can't understand, test results aren't then persisted in that file 🤷🏼

**Comment by super-jb** [comment]
> dotnet test --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage"

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage line-rate="1" branch-rate="1" lines-covered="0" lines-valid="0" branches-covered="0" branches-valid="0" complexity="NaN" version="0" timestamp="1716775553">
  <sources />
  <packages />
</coverage>
```

I have 2 unit test projects. I tried running the `test` command for a single project: same output. 
I'm truly baffled why this happening. I've read 23483294 articles and the code seems pretty similar in every blog, post, chatgpt-esque response, that I've seen

**Comment by super-jb** [comment]
@SeanKilleen, I'd really like to thank you for spending time looking into this... 
I *finaaaaaaaaaaaaaaaaaaaaaaaally* figured it out: `<PackageReference Include="xunit.analyzers" />`
There's some _incompatability_ with this specific package for `xUnit` 
I removed it, pushed changes, re-ran the build and... voila

**Comment by super-jb** [comment]
@SeanKilleen, I'd really like to thank you for spending time looking into this... 
I *finaaaaaaaaaaaaaaaaaaaaaaaally* figured it out: `<PackageReference Include="xunit.analyzers" />`
There's some _incompatability_ with this specific package for `xUnit` 
I removed it, pushed changes, re-ran the build and... voila

**Comment by SeanKilleen** [comment]
@super-jb whoa, so glad you figured it out!

If you can create a minimal reproduction using this repo I'm sure the xunit folks would be interested.

I appreciate you sharing here -- I learned something too!
